### ISSUE TITLE
(Not an Issue) Thank you!

### ISSUE THREAD

**Issue by mz1193** [GabePoel/KvYaru-Colors#1]
I couldn't find a "discussions" tab for this repository so feel free to close this when you see it, but I just wanted to give a big thank you for this theme set. I'm happy that I can finally have a uniform experience with Qt applications when using Yaru and its variants now.

**Comment by GabePoel** [comment]
OMG! These themes aren't really ready for prime time. But, I'm glad you like them! 😊
