### ISSUE TITLE
[request] also add yaru-remix?

### ISSUE THREAD

**Issue by Muqtxdir** [GabePoel/KvYaru-Colors#2]
Hi @GabePoel,

I do yaru-remix-themes, you can check my repository [here](https://github.com/Muqtxdir/yaru-remix). Is it okay to ask you, for also considering to make yaru-remix variants to your awesome kvantum themes? (it's okay if you don't want to do)

**Comment by GabePoel** [comment]
Done! 😊

**Comment by Muqtxdir** [comment]
Thanks @GabePoel
